### ISSUE TITLE
Document title in studio is displayed as JSON

### ISSUE THREAD

**Issue by sita-egy** [sanity-io/sanity-plugin-google-translate#6]
After installing the plugin and creating a schema with one field of type `localizedString` as follows
```
export default {
    title: "Product Tag",
    name: "product_tag",
    type: "document",
    fields: [
      {
        title: "Name",
        name: "name",
        type: "localizedString",
      }
    ]
}
```
Studio displays the product tag document title in JSON for example `name: {ar: عزل, en: isolation}`
<img width="820" alt="Screenshot 2021-09-02 at 01 19 55" src="https://user-images.githubusercontent.com/89701467/131762004-8230dbe3-bbb0-42ab-a1a3-b61878f9cdc9.png">

It would be better if Studio displays only the value of the default language automatically to look normal

**Comment by SimeonGriggs** [comment]
You can customise the `preview` key of your schema to use the default language name like so:

```js
  preview: {
    select: {
      title: 'name.ar',
    },
  }
```
